"""Typed configuration loading for all experiments.

Nearly all experiment behavior is driven by YAML so that the CLI remains simple:

    python -m frontier_interp.cli --config <path-to-yaml>

The code is intentionally explicit rather than clever because reproducibility is
more important here than minimizing boilerplate.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import yaml


@dataclass
class ModelSpec:
    registry_key: str
    enabled: bool = True
    revision: Optional[str] = None
    torch_dtype: Optional[str] = None
    attn_implementation: str = "eager"


@dataclass
class DatasetSpec:
    registry_key: str
    enabled: bool = True
    split: Optional[str] = None
    num_samples: Optional[int] = 64
    use_full_split: bool = False
    family: Optional[str] = None
    subset: Optional[str] = None
    add_choices: bool = True


@dataclass
class CrossFamilySplitSpec:
    name: str
    train_families: List[str] = field(default_factory=lambda: ["ALL"])
    eval_families: List[str] = field(default_factory=lambda: ["ALL"])
    enabled: bool = True


@dataclass
class DatasetScaleSpec:
    enabled: bool = False
    train_sizes: List[int] = field(default_factory=lambda: [16, 32, 64, 128])
    stratify_by_family: bool = True
    eval_uses_full_validation: bool = True




@dataclass
class SelfReflectionSpec:
    """Configuration for self-reflection experiments.

    These runs ask whether the target model can access its own behavior and
    mechanisms via two routes:
    1. self-probes attached to frozen target hidden states,
    2. prompted self-reports generated by the target model itself.
    """

    enabled: bool = False
    modes: List[str] = field(default_factory=lambda: [
        "self_probe_behavior",
        "self_probe_mechanism",
        "self_report_behavior",
        "self_report_mechanism",
    ])
    probe_arches: List[str] = field(default_factory=lambda: ["linear", "mlp"])
    probe_sizes: List[int] = field(default_factory=lambda: [64, 128])
    probe_steps: int = 300
    report_num_examples: int = 32
    report_max_new_tokens: int = 8
    report_temperature: float = 0.0

@dataclass
class SweepSpec:
    seeds: List[int] = field(default_factory=lambda: [0, 1, 2])
    interpreter_sizes: List[int] = field(default_factory=lambda: [64, 128])
    limit_layers: int = 4
    limit_heads: int = 8
    mechanism_types: List[str] = field(default_factory=lambda: ["attention_probs"])
    interpreter_arches: List[str] = field(default_factory=lambda: ["transformer"])
    controls: List[str] = field(default_factory=lambda: ["none"])
    cross_family_splits: List[CrossFamilySplitSpec] = field(default_factory=lambda: [CrossFamilySplitSpec(name="all_to_all")])
    dataset_scaling: DatasetScaleSpec = field(default_factory=DatasetScaleSpec)


@dataclass
class TrainingSpec:
    behavior_steps: int = 800
    mechanism_steps: int = 300
    batch_size: int = 4
    lr: float = 3e-4
    weight_decay: float = 1e-2
    max_prompt_len: int = 96
    interpreter_layers: int = 2
    interpreter_heads: int = 4
    dropout: float = 0.0
    behavior_objective: str = "kl_distill"  # options: kl_distill, restricted_choice_eval


@dataclass
class OutputSpec:
    root_dir: str = "outputs"
    run_name: str = "debug_run"
    save_checkpoints: bool = True
    save_plots: bool = True
    save_per_example_artifacts: bool = True
    save_model_cards: bool = True
    save_markdown_report: bool = True
    save_latex_tables: bool = True
    save_submission_bundle: bool = True
    submission_bundle_name: str = "submission_bundle"


@dataclass
class StatsSpec:
    bootstrap_iterations: int = 1000
    confidence_level: float = 0.95
    fdr_method: str = "bh"
    primary_metrics: List[str] = field(
        default_factory=lambda: ["mean_gap", "p90_gap", "frac_hard_heads"]
    )




@dataclass
class ValidationSpec:
    """Validation gates that decide which optional pathways are promoted.

    These gates let the repo distinguish between exploratory pathways that were
    merely executed and pathways that were strong enough to surface in the
    submission-facing summaries. The raw artifacts are always retained.
    """

    min_num_rows: int = 16
    self_report_min_parsed_ok: float = 0.80
    self_report_min_exact_match_to_target: float = 0.20
    self_report_min_exact_match_to_gold: float = 0.20
    self_report_mechanism_min_within_one: float = 0.35
    promote_only_validated_optional: bool = True


@dataclass
class RuntimeSpec:
    device: str = "auto"
    allow_fp16: bool = True
    trust_remote_code: bool = True
    compile_interpreters: bool = False
    # Frozen-target loading options for memory-constrained GPUs.
    # Use exactly one of load_in_8bit or load_in_4bit for bitsandbytes quantization.
    load_in_8bit: bool = False
    load_in_4bit: bool = False
    # "auto" is the safest default for quantized target models because Transformers/Accelerate
    # can place weights efficiently across available hardware.
    device_map: Optional[str] = None
    low_cpu_mem_usage: bool = True
    # Optional bitsandbytes knobs. Leave as null/none unless you know you need them.
    bnb_4bit_quant_type: str = "nf4"
    bnb_4bit_use_double_quant: bool = True
    bnb_4bit_compute_dtype: Optional[str] = "float16"


@dataclass
class ExperimentConfig:
    description: str
    models: List[ModelSpec]
    datasets: List[DatasetSpec]
    sweep: SweepSpec = field(default_factory=SweepSpec)
    training: TrainingSpec = field(default_factory=TrainingSpec)
    outputs: OutputSpec = field(default_factory=OutputSpec)
    stats: StatsSpec = field(default_factory=StatsSpec)
    runtime: RuntimeSpec = field(default_factory=RuntimeSpec)
    self_reflection: SelfReflectionSpec = field(default_factory=SelfReflectionSpec)
    validation: ValidationSpec = field(default_factory=ValidationSpec)


def _load_dataclass(cls, data: Dict[str, Any]):
    kwargs = {}
    for name in cls.__dataclass_fields__:
        if name not in data:
            continue
        value = data[name]
        if name == "models":
            kwargs[name] = [ModelSpec(**x) for x in value]
        elif name == "datasets":
            kwargs[name] = [DatasetSpec(**x) for x in value]
        elif name == "sweep":
            sweep_kwargs = dict(value)
            cfs = sweep_kwargs.get("cross_family_splits")
            if cfs is not None:
                sweep_kwargs["cross_family_splits"] = [CrossFamilySplitSpec(**x) for x in cfs]
            dss = sweep_kwargs.get("dataset_scaling")
            if dss is not None:
                sweep_kwargs["dataset_scaling"] = DatasetScaleSpec(**dss)
            kwargs[name] = SweepSpec(**sweep_kwargs)
        elif name == "training":
            kwargs[name] = TrainingSpec(**value)
        elif name == "outputs":
            kwargs[name] = OutputSpec(**value)
        elif name == "stats":
            kwargs[name] = StatsSpec(**value)
        elif name == "runtime":
            kwargs[name] = RuntimeSpec(**value)
        elif name == "self_reflection":
            kwargs[name] = SelfReflectionSpec(**value)
        elif name == "validation":
            kwargs[name] = ValidationSpec(**value)
        else:
            kwargs[name] = value
    return cls(**kwargs)



def load_config(path: str) -> ExperimentConfig:
    """Load a YAML config file into :class:`ExperimentConfig`."""
    with open(path, "r", encoding="utf-8") as f:
        raw = yaml.safe_load(f)
    return _load_dataclass(ExperimentConfig, raw)
